Cnto 8064
contacto-io/material-style-guide pull request #45
Opened 2024-01-16 13:26 UTC by kamlesh-nehra

2024-01-17 15:47 UTC, mimanshi-plivo requested changes

2024-01-17 15:47 UTC, mimanshi-plivo commented on package.json
> +    "rollup-plugin-uglify": "^6.0.4",
What do we need uglify for?

2024-01-23 07:43 UTC, mimanshi-plivo approved these changes

2024-03-08 10:15 UTC, samuellawerentz approved these changes

2024-03-08 10:15 UTC, merged